# Generated by Django 2.1 on 2020-04-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=100)),
                ('IP_address', models.CharField(max_length=100)),
                ('MAC_address', models.CharField(blank=True, max_length=100)),
                ('users_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='purchase Date(dd/mm/2020)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
