# Generated by Django 2.1 on 2020-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_computer_export_to_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_address', models.CharField(blank=True, max_length=100, null=True)),
                ('MAC_address', models.CharField(blank=True, max_length=30, null=True)),
                ('users_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date(mm/dd/2019)')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
